export const MENTORS = [
  {
    id: 1,
    name: "Nguyễn Quốc Đạt",
    role: "Founder Prom.vn",
    achievement: "Prompt Engineering Specialist",
    image: "/images/home/teams/1.jpg",
    description: "Context Engineering Specialist",
  },
  {
    id: 2,
    name: "Nguyễn Đình Hiếu - Hiếu AI",
    role: "Founder Ăn Ngủ Cùng AI",
    achievement: "247k followers Fanpage Ăn Ngủ Cùng AI",
    image: "/images/home/teams/2.jpg",
    description:
      "210K followers Tiktok Hiếu AI \n 14k sub Youtube Ăn Ngủ Cùng AI",
  },
  {
    id: 3,
    name: "Hưng AI Creator",
    role: "Founder COLOR MIND",
    achievement: "Tiktok: 100.000 người theo dõi",
    image: "/images/home/teams/3.jpg",
    description: "Fanpage: 20.000 người theo dõi",
  },
  {
    id: 4,
    name: "Hà Kiều Anh",
    role: "Founder HKA'STUDIO - 3D design",
    achievement: "Tốt nghiệp Savannah College of Art & Design (SCAD,GA)",
    image: "/images/home/teams/4.jpg",
    description: "Branding, poster, logo & motion graphic",
  },
  {
    id: 5,
    name: "Trần Minh Quân - QuanXMas",
    role: "AI Music / Sound Engineering",
    achievement: "Guitarist tại Spacespeaker",
    image: "/images/home/teams/5.jpg",
    description: "44 triệu view - Hit Me Up - BinZ",
  },
  {
    id: 6,
    name: "Đăng Văn Minh",
    role: "Chuyên gia chiến lược email marketing",
    achievement: "Ứng dụng AI lập kế hoạch, viết nội dung phân tích dữ liệu.",
    image: "/images/home/teams/6.jpg",
    description: "Triển khai thành công nhiều chuỗi email automation hiệu quả",
  },
  {
    id: 7,
    name: "TaiOn",
    role: "Founder AI-ker Community",
    achievement: "",
    image: "/images/home/teams/7.jpg",
    description: "40k followers Tiktok and Instagram",
  },
  {
    id: 8,
    name: "Nguyễn Duy Anh",
    role: "Founder Viewer",
    achievement: "Tích hợp AI vào quy trình tạo content xây dựng Agency",
    image: "/images/home/teams/8.jpg",
    description: "",
  },
] as const;
